version: '3'

services:
  # Databases
  keycloak.db:
    image: postgres

  catalog.db:
    image: postgres


  # Third-Party
  keycloak:
    image: quay.io/keycloak/keycloak:legacy

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  
  # Apps
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile


volumes:
  keycloak.db_data: 
  catalog.db_data: 